
System:
  log-level: DEBUG

Server:
  runmode: "debug"
  httpport: "8080"
  readtimeout: 60
  writetimeout: 60
  logsavepath: "logs/"
  logmaxage: 7
  logrotationtime: 1
  loglevel: "info"
  enabledswagger: true

Database:
  type: "mysql"
  user: "root"
  password: "1q2w3e4r!Q"
  host: "47.100.220.105:3306"
  name: "potato"
  tableprefix: "t_"

Redis:
  host: "47.100.220.105:6379"
  port: 6379
  password: "xxxxx"
  maxidle: 100
  maxactive: 3000
  idletimeout: 200
  db: 0
  connecttimeout: 1000
  readtimeout: 1000
  writetimeout: 1000

QiNiuYun:
  host: "http://rmctfv4vl.hn-bkt.clouddn.com"
  accessKey: "sJthUYIBW5Qgu2qALY-QXOKcno35cEcaapyUQYsj"
  secretKey: "Fwoyjq0BMQJY4a9pVvK4ayGifNSOyWoXTM-pXdu6"
  topicBucket: "test"
  commentBucket: ""
  replyBucket: ""
  defaultExpire: 7200

AuthCodeJwt:
  secret: "7MxYgO1I07XacrGLTeXDPj7rS6uABsInoQlQ3EDBU0Rff6K6ZALt9fbarKh4m5BOSFTZ"
  issuer: "demo"
  expire: 7200

RabbitMq:
  host: "amqp://guest:guest@localhost"
  exchange: "exchange"
  routingKey: "key"
  queue: "hello"

MqConsumer:
  host: "amqp://wangxiangbo:1q2w3e4r!Q@47.100.220.105:5672"
  exchange: "exchange"
  routingKey: "key"
  queue: "hello"